### PR TITLE
fix: Validate max 4 custom domains

### LINKED ISSUE #52: Validate custom domains during app creation
No more than 5 conditions can be added to a rule https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html

### PR DESCRIPTION
**Pull request by CuriousLearner**
Fixes #52 
Screenshot 2024-05-28 at 8 09 04 PM

### CODE REVIEW

File: stacks/app_pipeline.go [hunk 1]
```diff
@@ -509,7 +510,13 @@ func (a *AppStack) AskQuestions(sess *session.Session) error {
 						Message: "Custom Domain(s)",
 						Default: strings.Join(a.Parameters.Domains, "\n"),
 					},
-					Validate: survey.MaxLength(4),
+					Validate: func(val interface{}) error {
+						domains := strings.Split(val.(string), "\n")
+						if len(domains) > 4 {
+							return errors.New("only maximum of 4 custom domains are supported")
```
Comment (ipmb) [inline stacks/app_pipeline.go:516]: Can you update the error message to: `limit of 4 custom domains exceeded`

**Review by ipmb — CHANGES_REQUESTED** [review]

**Comment by ipmb** [comment]
Is the screenshot correct? It looks like the error popped up when only 2 domains were provided.

**Review by ipmb — APPROVED** [review]
