### PR TITLE
fix(reviewapp): Don't fail reviewapp commands if account flag is passed

### LINKED ISSUE #65: Present warning if account is passed in reviewapps command
## Description

Reviewapps depend on access to pipeline rather than access to account. While all other apps require account with `-c` reviewapps throws an error.

```
apppack -c lincoln-loop reviewapps destroy mytestpipeline:1
Error: unknown shorthand flag: 'c' in -c
Usage:
  apppack reviewapps destroy <pipeline:pr-number>

Flags:
  -h, --help   help for destroy

Global Flags:
      --aws-credentials   use AWS credentials instead of AppPack.io federation
      --debug             enable debug logging

unknown shorthand flag: 'c' in -c

```

This should throw a warning that account will be ignored but should still pass.

## Reason for task

Consistency in CLI commands

--- 

⏱ Estimated Level of Effort (LOE): _unestimated_

<details>
<summary><strong>Developer Checklist</strong></summary>

* [ ] Estimated LOE
* [ ] CI tests pass
* [ ] Deployed/tested in non-production environment
* [ ] Approved for deployment by project owner
* [ ] Deployed to production
</details>

### PR DESCRIPTION
**Pull request by CuriousLearner**
This makes the command compatible with other commands such that it accepts the account flag, but ignore it since for reviewapps the access is determined through pipeline rather than account.

Fixes #65

### CODE REVIEW

File: cmd/reviewapps.go [hunk 1]
```diff
@@ -140,4 +149,12 @@ func init() {
 	reviewappsCreateCmd.Flags().StringVar(&release, "release", "", "Specify a specific pre-release stack")
 	upgradeCmd.PersistentFlags().MarkHidden("release")
 	reviewappsCmd.AddCommand(reviewappsDestroyCmd)
+
+	reviewappsCmd.PersistentFlags().StringVarP(
+		&AccountIDorAlias,
+		"account",
+		"c",
+		"",
+		"AWS account ID or alias (not needed if you are only the administrator of one account)",
```
Comment (ipmb) [inline cmd/reviewapps.go:158]: Can we hide this for review apps? It shouldn't show up in the help list.

**Review by ipmb — CHANGES_REQUESTED** [review]

**Review by ipmb — APPROVED** [review]
