### PR TITLE
fix(reviewapp): Prevent non-existent app build

### LINKED ISSUE #44: Prevent build commands against a review app that doesn't exist
Check if a review app exists before allowing a user to run any `build *` command. The initial creation of a review app is an exception.

### PR DESCRIPTION
**Pull request by CuriousLearner**
Fixes #44 

Presents error on

```
apppack -a pipeline build start
```

& 

```
apppack -a pipeline:{pr} build start
```

if the review app does not exist.

### CODE REVIEW

**Review by ipmb — CHANGES_REQUESTED** [review]
`GetReviewApps` is going to be slow. You shouldn't need to iterate over all the values to see if this one exists, just try to read the specific parameter for this app.

File: app/app.go [hunk 1]
```diff
@@ -394,6 +394,17 @@ func (a *App) GetReviewApps() ([]*ReviewApp, error) {
 	return reviewApps, nil
 }
 
+func (a *App) ReviewAppExists() (bool, error) {
+	if !a.Pipeline {
+		return false, fmt.Errorf("%s is not a pipeline and cannot have review apps", a.Name)
+	}
+	_, err := SsmParameter(a.Session, fmt.Sprintf("/apppack/pipelines/%s/review-apps/pr/%s", a.Name, *a.ReviewApp))
```
Comment (ipmb) [inline app/app.go:401]: You might actually need to check the value of this. It should be JSON with a `status` key that needs a value of `created`. See https://github.com/apppackio/apppack/blob/main/cmd/reviewapps.go#L46

**Review by ipmb — CHANGES_REQUESTED** [review]

File: app/app.go (hunk 1 above)
Comment (ipmb) [reply app/app.go:401]: The parameter gets created when the PR is created at GitHub. That functionality is in the builder here, https://github.com/apppackio/apppack-codebuild-image/blob/main/builder/build/prebuild.go#L301-L304

In that case, the parameter will exist, but the review app will not.

**Review by ipmb — APPROVED** [review]
